- name: Pull and Run docker image
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /home/lenovo/anaconda3/bin/python
  tasks:
    - name: Pull image
      docker_image:
        name: superhakar/calculator
        source: pull
